ejercicio_2: ejercicio_2.cpp PoligonoIrregular.o
	g++ ejercicio_2.cpp PoligonoIrregular.o Coordenada.o -o ejercicio_2
PoligonoIrregular.o: PoligonoIrregular.cpp Coordenada.o PoligonoIrregular.h
	g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
